# Generated by Django 5.0 on 2023-12-16 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mientretencion', '0006_rename_codigo_juego_codigo_invent'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='precio',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
